ProductsService:
  type: HTTP
  config:
    # The FIRST deploy won't have any reference yet, use placeholder endpoint
    endpoint: ${cf:appsyncToHttp-gql-dev.HttpApiUrl}
    authorizationConfig:
      authorizationType: AWS_IAM
      awsIamConfig:
        signingRegion: ${self:provider.region}
        signingServiceName: execute-api
    iamRoleStatements:
    - Effect: Allow
      Action: 
      - execute-api:Invoke
      Resource: 
      # The FIRST deploy won't have any reference yet, use placeholder API ID
      - !Sub arn:aws:execute-api:${self:provider.region}:${AWS::AccountId}:${cf:appsyncToHttp-gql-dev.HttpApiId}/*/GET/products/*
      - !Sub arn:aws:execute-api:${self:provider.region}:${AWS::AccountId}:${cf:appsyncToHttp-gql-dev.HttpApiId}/*/GET/products
      - !Sub arn:aws:execute-api:${self:provider.region}:${AWS::AccountId}:${cf:appsyncToHttp-gql-dev.HttpApiId}/*/POST/products