ProductsService:
  type: HTTP
  config:
    # The FIRST deploy won't have any reference yet, use placeholder endpoint
    endpoint: ${cf:appsync-to-http/gql-dev.HttpApiUrl, 'https://google.com'}
    authorizationConfig:
      authorizationType: AWS_IAM
      awsIamConfig:
        signingRegion: ${self:provider.region}
        signingServiceName: execute-api
    iamRoleStatements:
    - Effect: Allow
      Action: 
      - execute-api:Invoke
      Resource: 
      - !Sub arn:aws:execute-api:${self:provider.region}:${AWS::AccountId}:${cf:appsync-to-http/gql-dev.HttpApiId, '12345'}/*/GET/products/*
      - !Sub arn:aws:execute-api:${self:provider.region}:${AWS::AccountId}:${cf:appsync-to-http/gql-dev.HttpApiId, '12345'}/*/GET/products
      - !Sub arn:aws:execute-api:${self:provider.region}:${AWS::AccountId}:${cf:appsync-to-http/gql-dev.HttpApiId, '12345'}/*/POST/products