# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI & Test

on:
  push:
    branches: [ master ]
  schedule:
  - cron: 0 7 * * *

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: read

jobs:
  build-deploy-test:
    runs-on: ubuntu-latest
    concurrency: build-deploy-test
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - name: Install dependencies
      run: npm ci
    - name: Run unit tests
      run: npm test
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
    - name: Run int tests
      run: npm run test:int
    - name: Deploy HTTP
      run: npm run deploy --config serverless.http.yml
    - name: Deploy GQL
      run: npm run deploy --config serverless.gql.yml
    - name: Run E2E Tests
      run: npm run test:e2e